version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: mibasededatos
      DATABASE_PORT: 3308  # Asegúrate de agregar esto si estás especificando el puerto en el código de tu aplicación
    volumes:
      - .:/app
    networks:
      - flask-mysql-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mibasededatos
    ports:
      - "3308:3306"  # Esto mapea el puerto 3308 de tu máquina al puerto 3306 del contenedor
    networks:
      - flask-mysql-network

networks:
  flask-mysql-network:
    driver: bridge
