services:
  app:
    build: .
    links:
      - db
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: personajes_test
      DATABASE_PORT: 3306  
    volumes:
      - .:/app
    depends_on:
      - db
    command: python /app/app.py  

  db:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: personajes_test
    ports:
      - "8080:3306" 
    networks:
      - default

networks:
  default:
    driver: bridge